### ISSUE TITLE
Getting subreddit information is blank. possible api bug

### ISSUE THREAD

**Issue by FireCubeStudios** [sirkris/Reddit.NET#104]
I tried reddit.Subreddit("askreddit").Sidebar and
reddit.Subreddit("askreddit").Title and
reddit.Subreddit("askreddit").Created and
reddit.Subreddit("askreddit").Description and
reddit.Subreddit("askreddit").ActiveUserCount

All of those functions return nothing its all empty. I dont know if I did something wrong or if its not supported.  I think sidebar isnt supported but the others should have worked. I tried with multiple different subreddits.

**Comment by FireCubeStudios** [comment]
ok the docs weren't clear but I did the about() function and its working. I will close if everything works.

**Comment by jeffward01** [comment]
This also stumped me a bit. thank you for creating this issue and posting the solution
