### ISSUE TITLE
Not necessarily an issue as much as clarification on monitoring objects

### ISSUE THREAD

**Issue by goodwinmcd** [sirkris/Reddit.NET#116]
What are "OldComments", "NewComments", "RemovedComments", and "AddedComments" objects in the monitoring callback function? I think I understand that RemovedComments are comments that were removed since the last monitoring event. OldComments are comments that were already detected by a previous monitoring event. 

Not sure of the difference between NewComments and AddedComments. I've dug through the docs and can't get clarification. If I can have this answered, I can create a PR that updates the wiki in the monitoring code example that explains this. 

Thanks.

**Comment by sirkris** [comment]
Hmm looks like I should add some documentation for that.  The difference
between NewComments and AddedComments is that NewComments is the full list
of comments returned by the API on the current monitoring event and
AddedComments is a list of just any comments that didn't appear before,
just as RemovedComments is a list of comments from the previous event that
are no longer present in the current one.

--Kris

**Comment by sirkris** [comment]
I recommend using AddedComments for detecting new comments and
RemovedComments for detecting removed comments.  The NewComments and
OldComments properties are used internally and probably wouldn't have much
practical use in userland code.

**Comment by goodwinmcd** [comment]
Awesome. That's great to know. Thank you!
