### ISSUE TITLE
Subreddit.Posts.MonitorNew() starts in the same place every time

### ISSUE THREAD

**Issue by kyleratti** [sirkris/Reddit.NET#117]
I am using Reddit.NET to monitor submissions to a subreddit. It seems, however, that every time my application starts it is retrieving a list of submissions from the same point in time and firing the `NewUpdated` event for each of them.

```fs
module Client =
    let create () =
        let reddit = new RedditClient(
                        AppConfig.getAppId,
                        AppConfig.getRefreshToken,
                        AppConfig.getAppSecret,
                        AppConfig.getAccessToken,
                        "Subreddit Scanner by github.com/kyleratti"
                        )
        reddit
```

```cs
private void Run()
{
	var _reddit = Client.create();
	var sub = _reddit.Subreddit("PublicFreakout").About();
	subs.Posts.NewUpdated += Posts_NewUpdated;
	subs.Posts.MonitorNew();
}

private void Posts_NewUpdated(object sender, Reddit.Controllers.EventArgs.PostsUpdateEventArgs e)
{
	var newPosts = e.Added;

	foreach(var post in newPosts)
	{
		Console.WriteLine(post.About().Fullname);
	}
}
```

Every time the application starts, it will immediately fire the `NewUpdated` event for the same reddit post.

I suspect this isn't a bug and I am misunderstanding something and that is causing the bot to authenticate in a certain state/point of time wherein those posts _are_ new, but I'd appreciate any guidance! I've been looking at this for a little while now and am stumped.

Thanks

PS - this is a wonderful library and I am grateful to your hard work on it!

**Comment by kyleratti** [comment]
Looking at the source, it seems like `MonitorNew()` will just call `GetNew` and fire an event for any posts that haven't been seen before.

https://github.com/sirkris/Reddit.NET/blob/ae1267b6e9f2360f41d1703af51cc64e27c07617/src/Reddit.NET/Controllers/SubredditPosts.cs#L562-L566

I am wondering if modifying my run function to call `GetNew()` and then discard the results would be the correct way/a sufficient workaround? That would seemingly set the `newPosts` parameter: https://github.com/sirkris/Reddit.NET/blob/ae1267b6e9f2360f41d1703af51cc64e27c07617/src/Reddit.NET/Controllers/SubredditPosts.cs#L118

```cs
private void Run()
{
	var _reddit = Client.create();
	var sub = _reddit.Subreddit("PublicFreakout").About();
	_ = sub.Posts.GetNew();
	sub.Posts.NewUpdated += Posts_NewUpdated;
	sub.Posts.MonitorNew();
}
```

**Comment by kyleratti** [comment]
Follow up: yes, retrieving new, discarding, and _then_ subscribing to the new feed has this working as intended.

**Comment by Alleyuuki** [comment]
@kyleratti did you happen to experience the same post being monitored multiple times?

**Comment by kyleratti** [comment]
> @kyleratti did you happen to experience the same post being monitored multiple times?

Could you clarify what you mean or provide an example? Once I started retrieving all of the posts before monitoring, things worked as expected.

**Comment by Alleyuuki** [comment]
```
 _ = sub.Posts.GetHot();
 sub.Posts.HotUpdated += C_postsUpdated;
 sub.Posts.MonitorHot();
```
My code looks like this, and I get events without problem, the only thing is that sometimes the same post gets monitored multiple times,  I attach a example from the console output, where you can see some perma links coming in multiple times
![Screenshot_20210113-000939_JuiceSSH](https://user-images.githubusercontent.com/77126471/104385585-cf077e80-5533-11eb-8a08-435cb526c1c6.jpg)

**Comment by kyleratti** [comment]
@Alleyuuki hmmm - I can't say I have noticed that. The only thing I could think of is I am calling `.About()` on the subreddit controller before using it to monitor:

```cs
	var sub = redditClient.Subreddit("MySub").About();
```

**Comment by Alleyuuki** [comment]
> @Alleyuuki hmmm - I can't say I have noticed that. The only thing I could think of is I am calling `.About()` on the subreddit controller before using it to monitor:
> 
> ```cs
> var sub = redditClient.Subreddit("MySub").About();
> ```

even with .About(); the same post comes trough multiple times, i might open an issue for this

**Comment by sirkris** [comment]
Calling About() is not required for monitoring to work; you should only
call it if you need to populate the Subreddit controller instance with that
subreddit's metadata, which is not required for monitoring.

Could you include the code you're using to generate that list of links?
Also, is the same post coming up twice in the same event or is it coming up
again in subsequent events?  I've noticed that monitoring sorts like Hot
and Controversial can get tricky because the Reddit API will sometimes
return a different set of posts on one query, another slightly different
set the next, then back to the first or some third one.  As a result, the
monitoring algo can be fooled into alerting the same post multiple times,
which I'm guessing is probably what's happening in your case.

This can be resolved by keeping track of permalinks that have already come
up and ignoring them on subsequent events.  The monitoring was mainly
designed for the New sort, so at some point we'll probably want to make
some improvements to compensate for this on the other sorts.

**Comment by Alleyuuki** [comment]
hi @sirkris thanks for the explanation,
here is my code https://github.com/Alleyuuki/RedditToTelegram/blob/master/RedditToTelegram/Program.cs#L47
the multiple posts are coming in in different events, i tought of keeping track of permalinks too, im fairly new with c# language soo my next question might be silly but,
```
 _ = sub.Posts.GetHot();
 sub.Posts.HotUpdated += C_postsUpdated;
  sub.Posts.MonitorHot();
```
can the `C_postsUpdated` function not be a static function? so i can access a list of permaLinks that will be a class variable?

**Comment by sirkris** [comment]
Nope it doesn't have to be static to consume the event.  As for the class
var, I'd recommend going with a HashSet<string> instead of List<string> for
performance reasons.

**Comment by sirkris** [comment]
I just merged in some changes that *should* fix this.  I basically implemented the caching we discussed here.  You don't have to do anything differently to make use of it.  I made caching enabled by default.  You can disable it by passing usecache: false to the monitor method.

The latest changes are available on the develop branch.  Could you check it out and let me know if this fixed your issue?

Thanks!

**Comment by kyleratti** [comment]
Linked against `1.4.0-develop` and removed my workaround, looks to be behaving as intended. Thanks!
