### ISSUE TITLE
Controllers.WikiPage.SaveChanges throws HTTP 409 Conflict

### ISSUE THREAD

**Issue by kyleratti** [sirkris/Reddit.NET#118]
I am attempting to edit a Wiki page by replacing its existing contents with an entirely new string. Every time I attempt this, I am getting an `HTTP 409 Conflict` error code.

```fs
let savePage (reddit: RedditClient) (subreddit: string) (page: string) (newContents: string) =
	let wiki = (reddit.Subreddit subreddit).Wiki
	let page = (wiki.GetPage page).About()
	page.ContentMd <- newContents
	page.SaveChanges "test save"

savePage reddit "PublicFreakout" "test" "this is a test of the API"
```

If I inspect the network request when editing a wiki page from the browser, it appears to always send a `previous` revision ID. It's unclear from the [reddit API docs](https://www.reddit.com/dev/api#POST_api_wiki_edit) whether this is required, however the call to [WikiPage.SaveChanges(...)](https://github.com/sirkris/Reddit.NET/blob/ae1267b6e9f2360f41d1703af51cc64e27c07617/src/Reddit.NET/Controllers/WikiPage.cs#L213) seems to indicate that the `previous` parameter is optional.

I've been digging through the `WikiPage` model but don't see a way to retrieve the latest revision ID from any public or non-public members.

I'd love a nudge in the right direction here. Thanks!

**Comment by kyleratti** [comment]
I was able to work around this by calling `Controllers.WikiPage.Revisions()`, taking the first result, and grabbing its ID: https://github.com/kyleratti/domain-reputation/blob/44d1d4f9d962d56d009b040b21062a437eca542a/RedditClient/Client.fs#L79

Then by calling `Controllers.WikiPage.Edit(editReason, newContents, latestRevision.id)` I can get the edits to go through.

I don't want to close this however as it seems like I may be missing something or perhaps there is room to improve the docs (happy to submit a PR once I understand the behavior).

There's also a possibility that `Controllers.WikiPage.SaveChanges(reason, revision = "")` contains a bug - if the revision ID is required, I would think that revision parameter should be optional. Regardless, the function doesn't seem to actually do anything with the `revision` parameter? https://github.com/sirkris/Reddit.NET/blob/ae1267b6e9f2360f41d1703af51cc64e27c07617/src/Reddit.NET/Controllers/WikiPage.cs#L213

**Comment by sirkris** [comment]
Hmm let me investigate.  Been awhile since I wrote this one.  I do know that the API requires the last revision ID for any edit request (and no, it makes no sense to me, either), but the revision parameter shouldn't just be ignored.  I'll take a look.

**Comment by sirkris** [comment]
I think you're right on this.  When I first wrote this, I probably assumed that the previous revision ID was optional, as requiring the ID of the last revision doesn't make a whole lot of sense.  I mean, I understand giving people the option to specify an earlier starting revision ID, but I think it should just assume the last one if not specified.  

Anyway, I'll go ahead and make previous a required parameter.  I'll also make a point of including this in the tutorials I plan to make for Issue #123.

Please feel free to re-open this if you think I've missed anything.

**Comment by kyleratti** [comment]
Awesome, thanks @sirkris!
