### ISSUE TITLE
An instant ban came to my Subreddit

### ISSUE THREAD

**Issue by MyNameIsSoftIce** [sirkris/Reddit.NET#141]
An instant ban came to my Subreddit for such a line 

var MyJson = Reddit.Models.Widgets.WidgetImageUploadS3("C:\\b.jpg", "image/jpeg");

The picture shows flowers.

What is the reason?

**Comment by sirkris** [comment]
There's no reason I'm aware of that would cause a widget upload to result
in a ban.  This would have occurred at the API level, incependent of the
Reddit.NET library.  I recommend you post your question over at r/redditdev.

--Kris

**Comment by sirkris** [comment]
Closed due to inactivity.  Please feel free to reopen if you still need help.
