### ISSUE TITLE
RefreshToken from AuthRetriever not working

### ISSUE THREAD

**Issue by Echarnus** [sirkris/Reddit.NET#145]
I generated both an access and a refresh token via the AuthRetriever, the access token is working while the refresh token is not using the RedditClient. I immediately receive 401 Unauthorized.

**Comment by sirkris** [comment]
Can you be more specific?  What error are you getting?

**Comment by sirkris** [comment]
Closed due to lack of feedback and inability to reproduce reported issue.  Please feel free to reopen this if the issue persists.
