### ISSUE TITLE
How to Post to User Profile?

### ISSUE THREAD

**Issue by RehanSaeed** [sirkris/Reddit.NET#146]
I'd like to create link posts in my user profile under: https://www.reddit.com/user/muhammadrehansaeed. Is this possible? If so, how?

**Comment by sirkris** [comment]
Yes this can be accomplished by loading the profile into a Subreddit object with "u_" followed by the username of the profile you want to post to (anything other than your own should throw an exception).

For example:

`var profileLinkPost = reddit.Subreddit("u_KrisCraig").LinkPost("https://xkcd.com/308/").Submit()`

If you want to dynamically post to the profile of whoever the active user is, then you can do this:

`var profileLinkPost = reddit.Subreddit($"u_{reddit.Account.Me.Name}").LinkPost("https://xkcd.com/308/").Submit();`

**Comment by sirkris** [comment]
Updated docs.
