### ISSUE TITLE
Add Images to posts?

### ISSUE THREAD

**Issue by nmills3** [sirkris/Reddit.NET#147]
Is it possible to upload a set of images to reddit with this library?

**Comment by sirkris** [comment]
At present, no.  When the library was written, image-type posts weren't yet supported by the API.  I just checked the docs and they do now list "image" as a valid type in POST /api/submit, but I'm not seeing any field for the file data, nor am I able to find an endpoint for uploading an image.

This would be a great question to post over at https://www.reddit.com/r/redditdev.  If the API ever adds support for image uploads, I'll of course be happy to add it to the library.
