### ISSUE TITLE
Document approving posts/comments and marking as spam

### ISSUE THREAD

**Issue by itsWindows11** [sirkris/Reddit.NET#162]
I can't seem to find functionality for approving posts/comments and marking them as spam, is it planned?

**Comment by sirkris** [comment]
That functionality has always been in RDN:

```
// approve
(Controllers.Post)post.Approve();

// mark as spam
(Controllers.Post)post.Remove(spam: true);

**Comment by sirkris** [comment]
Reopened to add this to the docs.

**Comment by sirkris** [comment]
Examples added.

**Comment by Aeroverra** [comment]
what about comments?
