### ISSUE TITLE
How to retrieve token for bot accounts

### ISSUE THREAD

**Issue by hallidev** [sirkris/Reddit.NET#168]
Hello,

I have a bot that runs 24/7 as a console app that's basically monitoring comments and edits. I'm using this old / unmaintained Reddit API wrapper:
https://github.com/CrustyJew/RedditSharp-DEPRECATED-

My hope was that I'd be able to swap out their library for yours, but I'm embarrassed to say struggling with token retrieval using this library.

This is what token retrieval looks like using RedditSharp:

```
var botWebAgent = new BotWebAgent
(
	"username",
	"password",
	"clientId",
	"clientSecret",
	 "redirectUri"
);

var reddit = new RedditSharp.Reddit(botWebAgent, true);
```

It really was as easy at that. RedditSharp takes the bot's credentials and retrieves a token behind the scenes. There is no interactive browser based login. Since the bot runs unattended and even starts up automatically across server reboots, there can't be a browser involved in token retrieval.

Is there any equivalent of this sort of login with this library?

Thanks!

**Comment by Martin-Ludwig** [comment]
I had the same issue. I solved it by creating a token on this site: https://not-an-aardvark.github.io/reddit-oauth-helper/
Make sure you set the redirect url in your bot account. You can find them here: https://ssl.reddit.com/prefs/apps/

Then you have a refresh and access token for your RedditClient in your code.

**Comment by hallidev** [comment]
Thanks for the tip!

**Comment by sirkris** [comment]
In case anybody finds this on Google, please note that OP is referencing an issue with RedditSharp, NOT Reddit.NET.  I am in no way affiliated with the RedditSharp project and this forum is not intended for issues or questions relating to that library.

There are tutorials on how to do this using Reddit.NET.  Though I'm hardly an unbiased observer here, I would strongly recommend you consider switching.  =)

**Comment by hallidev** [comment]
I was using RedditSharp as an example of how easy it was to retrieve a token for bots using that library. As far as I’m aware, it’s impossible to achieve the same thing using Reddit.NET. 

If there’s an article that explains how to do it, I was unable to find it despite looking pretty thoroughly. 

Note that the workaround mentioned by @Martin-Ludwig isn’t workable in my scenario.

**Comment by sirkris** [comment]
You are very much mistaken.  Reddit.NET comes with what's known as the AuthTokenRetrieverLib.  This library is what you're looking for.

Please note that Reddit.NET is oAuth-only, meaning it does NOT (and will not) support password-based authentication due to it being ridiculously unsecure.  Instead, you can use AuthTokenRetrieverLib to request a new refresh token for a given app ID, then you use that to authenticate.

Check out this section of the docs for more info:

https://github.com/sirkris/Reddit.NET#solution-projects
