### ISSUE TITLE
No User Saved Posts Implementation

### ISSUE THREAD

**Issue by Hi-ImKyle** [sirkris/Reddit.NET#173]
Looking to get the current users saved posts but there doesn't appear to be any implementation for that.

**Comment by eduardobragaxz** [comment]
redditClient.Account.Me.GetPostHistory("saved", _other arguments_);

**Comment by sirkris** [comment]
@eduardobragaxz is correct.  Here's a practical example that retrieves my saved posts (do I even have any?) and the authenticated user's:

```
IList<Post> krisCraigSavedPosts = reddit.User("KrisCraig").GetPostHistory("saved");
IList<Post> mySavedPosts = reddit.Account.Me.GetPostHistory("saved");

```
