### ISSUE TITLE
Add Post comment not working

### ISSUE THREAD

**Issue by RGrillo** [sirkris/Reddit.NET#187]
I am trying to use the following command and it's not working

            // Retrieve the post
            var post = _redditClient.Post("1eyf7ib").About();

            // Reply to the post
            post.Comment("This is my reply to the post!");

Reddit.Exceptions.RedditControllerException: 'Unable to retrieve post data.'

**Comment by sirkris** [comment]
It looks like you're not passing a valid Thing ID to Post.  Try adding "t3_" in front of your Post ID and see if that fixes it.

**Comment by RGrillo** [comment]
Thanks for your feedback,
Ok now we are retrieving  the post, BUT... no comment was added to the referenced post


PS: one thing that I notice that in the Post object we have this
                return (string.IsNullOrEmpty(id) && !string.IsNullOrEmpty(fullname)
                    ? fullname.Substring(3)
                    : id);

in this case we should not change it and stead just retrieve the fullname as the Id or not Substring...

**Comment by sirkris** [comment]
> Ok now we are retrieving the post, BUT... no comment was added to the referenced post

That's because you're creating a comment object but not actually submitting it to the Reddit API.  I created the Reply method for this purpose; it creates the comment object AND submits it to Reddit.

So changing your code to this should work:

```c#
post.Reply("This is my reply to the post!");
```

> in this case we should not change it and stead just retrieve the fullname as the Id or not Substring...

What you're looking at is basically just a convenience I added in case the ID field is populated but Fullname is not.  Since Fullname is literally just "t3_" + ID, it seemed like an easy win.

The reason we can't pass an ID to Post is because it's expecting a Fullname string.  But when it passes that Fullname to the API, it's rejected as invalid.  I suppose we could add some code to automatically add the prefix, though that would come at a slight performance hit since we'd have to check the beginning of the string every time that overload of Post is called.

**Comment by RGrillo** [comment]
Magic, thank you very much, if this helps I have on my system a class called DigestedRedditPostModel that you could use on your code, if you agree I can create a pull request on it, and it should be really helpful. 

public class DigestedRedditPostModel
{
    public DigestedRedditPostModel()
    {

    }

    public DigestedRedditPostModel(Post post, string keyword)
    {
        Title = post.Title;
        URL = "https://reddit.com" + post.Permalink;
        Content = post.Listing.SelfText;
        SubReddit = post.Subreddit;
        PostedDate = DaysSincePost(post.Created);
        Author = post.Author;
        Keyword = keyword;
        Id = "t3_" + post.Id;
        Created = post.Created;

        if (!string.IsNullOrWhiteSpace(post.Listing.URL))
        {
            ImageURL = post.Listing.URL;
        }
    }

    public string Title { get; set; } = string.Empty;
    public string Author { get; set; } = string.Empty;
    public string Id { get; set; } = string.Empty;
    public string URL { get; set; } = string.Empty;
    public string ImageURL { get; set; } = string.Empty;
    public string Content { get; set; } = string.Empty;
    public string SubReddit { get; set; } = string.Empty;
    public string PostedDate { get; set; } = string.Empty;
    public DateTime Created { get; set; } = DateTime.Now;
    public string Keyword { get; set; } = string.Empty;
    public bool ShowReply { get; set; } = false;
    public string Answer { get; set; }

    private string DaysSincePost(DateTime postCreatedAt)
    {
        string daysSincePost = "";
        return daysSincePost = (DateTime.Now - postCreatedAt) switch
        {
            TimeSpan diff when diff.TotalDays >= 1 => $"{(int)diff.TotalDays}d",
            TimeSpan diff when diff.TotalHours >= 1 => $"{(int)diff.TotalHours}h",
            _ => "1h" // fallback to 1 hour if difference is less than 1 hour
        };
    }
}



Many Tahnks
