### ISSUE TITLE
Figure out what all the different numbers mean in the JSON return of GET /r/subreddit/about/traffic

### ISSUE THREAD

**Issue by sirkris** [sirkris/Reddit.NET#42]
There's no documentation on this that I can find and the fields are just arrays of unlabeled integers.  Right now, the traffic endpoint just returns a buttload of numbers without any context as to what each represents.

Here's an example:

{"day":[[1540339200,0,0,0],[1540252800,0,0,0],[1540166400,68,75,0],[1540080000,26,45,2],[1539993600,79,160,1],[1539907200,107,154,1],[1539820800,80,135,1],[1539734400,52,79,0],[1539648000,10,14,2],[1539561600,14,27,1],[1539475200,34,60,0],[1539388800,86,119,0],[1539302400,104,135,1],[1539216000,30,48,1],[1539129600,83,120,0],[1539043200,56,79,0],[1538956800,50,65,1],[1538870400,62,96,0],[1538784000,73,88,0],[1538697600,7,9,0],[1538611200,72,112,6],[1538524800,44,61,1],[1538438400,28,51,0],[1538352000,43,55,0],[1538265600,24,55,1],[1538179200,21,30,1],[1538092800,14,62,1],[1538006400,30,51,1],[1537920000,14,32,1],[1537833600,47,96,0],[1537747200,38,58,0],[1537660800,26,39,0],[1537574400,58,86,0],[1537488000,34,50,0],[1537401600,27,34,0],[1537315200,34,59,0],[1537228800,33,66,1],[1537142400,52,92,1],[1537056000,39,70,1],[1536969600,12,18,0],[1536883200,17,25,2],[1536796800,27,43,0],[1536710400,24,39,0],[1536624000,45,54,0],[1536537600,40,45,3],[1536451200,16,22,1],[1536364800,13,26,0],[1536278400,7,16,0],[1536192000,40,47,1],[1536105600,20,39,1],[1536019200,18,29,3],[1535932800,21,47,1],[1535846400,14,26,0],[1535760000,26,40,2],[1535673600,25,30,0],[1535587200,23,54,0],[1535500800,38,53,0]],"hour":[[1540360800,0,0],[1540357200,0,0],[1540353600,0,0],[1540350000,0,0],[1540346400,3,7],[1540342800,0,0],[1540339200,0,0],[1540335600,0,0],[1540332000,0,0],[1540328400,0,0],[1540324800,0,0],[1540321200,0,0],[1540317600,0,0],[1540314000,0,0],[1540310400,0,0],[1540306800,0,0],[1540303200,0,0],[1540299600,0,0],[1540296000,0,0],[1540292400,0,0],[1540288800,0,0],[1540285200,0,0],[1540281600,0,0],[1540278000,0,0],[1540274400,0,0],[1540270800,0,0],[1540267200,0,0],[1540263600,2,11],[1540260000,0,0],[1540256400,0,0],[1540252800,0,0],[1540249200,0,0],[1540245600,0,0],[1540242000,0,0],[1540238400,0,0],[1540234800,0,0],[1540231200,0,0],[1540227600,0,0],[1540224000,0,0],[1540220400,0,0],[1540216800,12,12],[1540213200,20,23],[1540209600,0,0],[1540206000,0,0],[1540202400,0,0],[1540198800,0,0],[1540195200,0,0],[1540191600,0,0],[1540188000,0,0],[1540184400,0,0],[1540180800,0,0],[1540177200,0,0],[1540173600,0,0],[1540170000,0,0],[1540166400,0,0],[1540162800,0,0],[1540159200,0,0],[1540155600,0,0],[1540152000,0,0],[1540148400,0,0],[1540144800,0,0],[1540141200,0,0],[1540137600,0,0],[1540134000,0,0],[1540130400,0,0],[1540126800,0,0],[1540123200,0,0],[1540119600,0,0],[1540116000,0,0],[1540112400,0,0],[1540108800,0,0],[1540105200,0,0],[1540101600,0,0],[1540098000,0,0],[1540094400,0,0],[1540090800,0,0],[1540087200,0,0],[1540083600,0,0],[1540080000,0,0],[1540076400,0,0],[1540072800,3,18],[1540069200,0,0],[1540065600,0,0],[1540062000,0,0],[1540058400,3,7],[1540054800,0,0],[1540051200,0,0],[1540047600,0,0],[1540044000,4,8],[1540040400,0,0],[1540036800,0,0],[1540033200,0,0],[1540029600,0,0],[1540026000,2,8],[1540022400,0,0],[1540018800,2,7],[1540015200,0,0]],"month":[[1538352000,797,1875],[1535760000,609,1545],[1533081600,758,1703],[1530403200,1289,3238],[1527811200,887,2263],[1525132800,753,1912],[1522540800,770,1977],[1519862400,998,2756],[1517443200,791,2166],[1514764800,828,2211],[1512086400,2015,3914],[1509494400,1738,4496]]}

The first number in each sequence is almost certainly a timestamp.  The other two must be some sort of quantification of subreddit traffic (pageview metrics, perhaps?).

**Comment by drch-** [comment]
under the "days" key its: uniques, pageviews, subscriptions for the past 60 days or so
under "hours" and "month" its just: uniques, pageviews

**Comment by sirkris** [comment]
Thanks!  Now I can finally make the traffic data readable.
