### ISSUE TITLE
RedditInvalidOptionException: that option is not valid

### ISSUE THREAD

**Issue by JamieMagee** [sirkris/Reddit.NET#59]
I'm having issues using authenticated endpoints, specifically `Subreddit.Update()`. I created my script app, and generated my refresh token using the provided oauth handler.

My code is something like this

```csharp
var r = new RedditAPI(AppId, RefreshToken, AppSecret);
var subreddit = r.Subreddit("...").About();
subreddit.Sidebar = "Hello, world!";
try
{
  subreddit.Update();
}
catch (RedditInvalidOptionException e)
{

}
```

I've verified that `r.Account.Me.Name` returns the correct name, and that user is a moderator on the subreddit that I'm trying to update. Am I missing something?

**Comment by sirkris** [comment]
It's difficult to say for certain from here, but I would start by checking your OAuth scopes to make sure you have the modconfig scope.  If you're lacking that, then the API will reject that endpoint while authentication itself still works.

**Comment by sirkris** [comment]
No response in nearly 6 months so I'm closing this.  Please feel free to re-open if you're still having problems.
