### ISSUE TITLE
Unable to retrieve paginated Flair list

### ISSUE THREAD

**Issue by JohnnyPrimus** [sirkris/Reddit.NET#62]
When retrieving paginated things, "after" is accessed via (presuming my understanding is correct) the "FullName" property. FlairListResult does not provide such a property.

Watching in fiddler, reddit returns a "next" property with the array of flairs. If I grab the value of "name" manually, and supply that as the "next" arg, the right thing happens and the next page of results is returned. On the final page a "prev" property is returned instead of next.

**Comment by JohnnyPrimus** [comment]
pull request w/ basic paging #64

**Comment by MingweiSamuel** [comment]
I also need this. Really basic feature that is missing.

**Comment by sirkris** [comment]
Nice catch!  I'll work this into the next release.

**Comment by JohnnyPrimus** [comment]
Cheers thx!

**Comment by sirkris** [comment]
@JohnnyPrimus Could you post the full JSON return you're getting from Reddit?  I want to make sure we have the property names correct and in the right places and all that.  Thanks!

**Comment by MingweiSamuel** [comment]
I can get that

`?after=&before=&limit=5&count=0`
```
{
    "users": [
        {
            "flair_css_class": "mastery-7 masteryText",
            "user": "vogueboy",
            "flair_text": "55,522 Brazil"
        },
        {
            "flair_css_class": "rank-unranked mastery-2",
            "user": "Acyclovir",
            "flair_text": "(◕‿◕✿)"
        },
        {
            "flair_css_class": "teaser1 mastery-7",
            "user": "dstrb3d1",
            "flair_text": null
        },
        {
            "flair_css_class": "zyra",
            "user": "tsularesque",
            "flair_text": ""
        },
        {
            "flair_css_class": "mastery-4",
            "user": "SpuckUnites",
            "flair_text": "Want More Shrooms?"
        }
    ],
    "next": "t2_39ay9"
}
```

`?after=t2_39ay9&before=&limit=5&count=5` (count doesn't seem to matter)
```
{
    "prev": "t2_3g0v5",
    "users": [
        {
            "flair_css_class": "r rank-gold mastery-7 masteryText",
            "user": "asdfqewr",
            "flair_text": "272,642"
        },
        {
            "flair_css_class": "mastery-6 masteryText",
            "user": "Indivicivet",
            "flair_text": "43,206"
        },
        {
            "flair_css_class": "newdawn3",
            "user": "Be3Al2Si6O18",
            "flair_text": ""
        },
        {
            "flair_css_class": "mastery-7 masteryText",
            "user": "itwasstinky",
            "flair_text": "421,084"
        },
        {
            "flair_css_class": "rank-gold mastery-1 masteryText",
            "user": "Donnyboy",
            "flair_text": "295 I'm running at you, the long way around."
        }
    ],
    "next": "t2_3sssq"
}
```

**Comment by JohnnyPrimus** [comment]
+1 thanks @MingweiSamuel 

One other thing: on the last page there is no "next". It is "prev" 

[https://github.com/sirkris/Reddit.NET/pull/64/files](FlairListResultsContainer.cs from pull req 64) is example of where they successfully deserialized for me. if you need caps for the "prev" thing happy to provide

**Comment by sirkris** [comment]
Thanks!  I merged in the fix.  If you could, please pull the develop branch and let me know if it works for you now.

**Comment by JohnnyPrimus** [comment]
Works like a charm, thanks!
