### ISSUE TITLE
Access token is never renewed

### ISSUE THREAD

**Issue by matteofabbri** [sirkris/Reddit.NET#63]
The result is that after one hour the the client stop to work.
I tryed to do some debug, Reddit.Models.Internal.Request.RefreshAccessToken is performed only when is too late and requests are already declined by the server.

I tryed to remove any check on performing the update but doesn't seems to help

        private IRestResponse GetResponse(IRestResponse res, ref RestRequest restRequest)
        {
            int serviceRetry = 3;
            restRequest = RefreshAccessToken(restRequest);
            res = RestClient.Execute(restRequest);

            return res;
        }

**Comment by sirkris** [comment]
It shouldn't be too late to request a new access token unless you're waiting a really, really long time.  What response do you get when you try to obtain a new access token using the refresh token?

**Comment by matteofabbri** [comment]
one hour, is written in the first line of the issue.

**Comment by sirkris** [comment]
In that case, it's not too late.  If the access token expires (which it does after an hour), you pass the refresh token and the Reddit API gives you a new access token to use for another hour, and so-on.  The refresh token shouldn't ever expire on its own.

Could you please post the actual response you're getting back from the Reddit API when this rejection occurs?  It usually includes some kind of error message that would be helpful to see.  You can see the full response if you run it in debug mode.

**Comment by matteofabbri** [comment]
The token was 100% permanent. 
Btw using the latest nuget looks like is fixed.
Tnx
