### ISSUE TITLE
How to read post contents?

### ISSUE THREAD

**Issue by Somfic** [sirkris/Reddit.NET#66]
I am trying to read the actual post. I've got reading comments and the title working, but I cannot find the BodyHtml for the actual post itself?

**Comment by sirkris** [comment]
My guess is you're trying to use the Post class for this.  The problem is that Post is just the base class for two other classes, LinkPost and SelfPost.  In this case, what you're looking for is the SelfPost.SelfText property.

**Comment by Somfic** [comment]
Oh, okay. What'd be the best way to go from `Post` to `SelfPost`?
