### ISSUE TITLE
Reddit local timestamps are parsed incorrectly

### ISSUE THREAD

**Issue by louistio** [sirkris/Reddit.NET#68]
Some Reddit endpoints use attributes with both a local and a UTC timestamp, for example in a post you'll have `created` and `created_utc`. The local timestamp supposedly is only kept for legacy reasons and should not be used because it adds an unpredictable timezone offset. The library incorrectly parses it as a UTC timestamp, and then uses it as the main value to build the `Controllers` objects, leading to the controller properties representing the wrong moment in time.

In the `Post` object, the `Created` property corresponds to the incorrectly parsed `created` timestamp instead of `created_utc`, which means it is off by several hours depending on Reddit's offset. My offset is -04:00 (EST), but since the library both adds the timestamp to UTC 0 and parses it as a `DateTimeKind.Utc`, the `Created` property ends up 8 hours after the post was created.

You can easily recreate this with any Reddit post (assuming you don't live in an area where Reddit returns +00:00 offset for local timestamps), or just by parsing manually using the library's `TimestampConvert`. Notice how parsing these real values from the Reddit API leads to both `DateTime`s representing different points in time:

```csharp
[Serializable]
public class Post
{
    [JsonProperty("created")]
    [JsonConverter(typeof(TimestampConvert))]
    public DateTime Created;

    [JsonProperty("created_utc")]
    [JsonConverter(typeof(TimestampConvert))]
    public DateTime CreatedUTC;
}


var parsed = JsonConvert.DeserializeObject<Post>("{\"created\": 1560051756.0, \"created_utc\": \"1560022956.0\"}");
```

**Comment by sirkris** [comment]
Nicely done, thanks!  Merged into 1.2.
