### ISSUE TITLE
Is there a way to get award information?

### ISSUE THREAD

**Issue by Somfic** [sirkris/Reddit.NET#70]
I'd like to get a list of all awards (gold, silver) a post has gotten. Is there a way to do this, or is this not supported by Reddit?

**Comment by sirkris** [comment]
The return for LinksAndComments.Info includes a "gildings" variable that might contain what you're looking for.

**Comment by Somfic** [comment]
Amazing.

What'd be the best way to get the `Gildings` property? I've tried creating a new `Reddit.Things.Post` from a `Reddit.Controllers.SelfPost` object, but the `Gildings` property is always `null`. The post has a few awards, however.

**Comment by sirkris** [comment]
In v1.3 (now on develop), you'll be able to access the awards more easily using the new Awards controller structure:

```c#
int postSilver = post.Awards.Silver;
int postGold = post.Awards.Gold;
int postPlatinum = post.Awards.Platinum;
int postTotalAwards = post.Awards.Count;

int commentSilver = comment.Awards.Silver;
int commentGold = comment.Awards.Gold;
int commentPlatinum = comment.Awards.Platinum;
int commentTotalAwards = comment.Awards.Count;
```
