### ISSUE TITLE
No "after" parameter for comments

### ISSUE THREAD

**Issue by jbhaywood** [sirkris/Reddit.NET#73]
I don't see a way to get more than the first page of comments for a particular post since none of the Comments.Get methods take an "after" parameter. I had assumed I could apply the [Paginated Posts](https://github.com/sirkris/Reddit.NET/blob/master/docs/examples/cs/Paginated%20Posts.md) example to comments, but that doesn't seem possible. Is there another way or is this a missing feature?

**Comment by sirkris** [comment]
The Reddit API doesn't have an "after" parameter for comments.  It would be a lot easier if it did, that's for sure.  Instead, you have to make use of the MoreChildren endpoint.

**Comment by sirkris** [comment]
Related: #94

**Comment by sirkris** [comment]
The bug has been fixed and merged into 1.3 (you can find the fix on the develop branch for the time being).  Accessing nested comment reply trees should be a lot easier now.

See the newly-added comment workflow tests for examples.
