### ISSUE TITLE
How to get the flair string of a post?

### ISSUE THREAD

**Issue by FireCubeStudios** [sirkris/Reddit.NET#77]
Couldn't figure out how to get the flair of a post. examples didn't show how to do this either but there is probably a way.

**Comment by sirkris** [comment]
I'll add it to the LinkPost controller in 1.3.  In the meantime, you can access the link flair text like so:

var flairText = myLinkPost.Listing.LinkFlairText;

**Comment by FireCubeStudios** [comment]
ok
