### ISSUE TITLE
BuildException always throws System.ArgumentException: Argument passed in is not serializable

### ISSUE THREAD

**Issue by MingweiSamuel** [sirkris/Reddit.NET#81]
Exception.Data can only take serializable values: https://csharp.2000things.com/2013/07/16/888-objects-added-to-exceptions-data-dictionary-must-be-serializable/

RestResponse is not serializable, so this always throws an exception and we lose any useful debugging information from the intended exception.

**Comment by sirkris** [comment]
Merged into 1.3.
