### ISSUE TITLE
Add `raw_json=1` to fix HTML entity encodings

### ISSUE THREAD

**Issue by MingweiSamuel** [sirkris/Reddit.NET#83]
https://www.reddit.com/dev/api#response_body_encoding

Thought it was a reddit bug, extra info here: https://www.reddit.com/r/bugs/comments/cyz8x1
But turns out its intended behavior. Currently this library doesn't do anything to fix the HTML entities so it should either use `raw_json=1` or HTML decode string values (probably the former is better)

**Comment by sirkris** [comment]
Merged into 1.3.  All tests passing.
