### ISSUE TITLE
SnoomojiContainer missing subreddit-specific emoji

### ISSUE THREAD

**Issue by MingweiSamuel** [sirkris/Reddit.NET#84]
https://www.reddit.com/dev/api/#GET_api_v1_{subreddit}_emojis_all
The response has 2 keys: - Reddit emojis (snoomoji) - SR emojis

So the key `"snoomoji"` is included but is missing the other field. The other fields name is equal to the subreddit id, which is a little inconvenient. Need a way to access that field.

Also given that, `SnoomojiContainer` probably isn't the best name for the class.

**Comment by sirkris** [comment]
Merged into 1.3.
