### ISSUE TITLE
Feature: allow user to set useragent header

### ISSUE THREAD

**Issue by MingweiSamuel** [sirkris/Reddit.NET#87]
Implementation: remove this line https://github.com/sirkris/Reddit.NET/blob/master/src/Reddit.NET/Models/Internal/Request.cs#L154
And add RestClient-level user-agent as described here: https://github.com/restsharp/RestSharp/issues/787
Would need to be set in https://github.com/sirkris/Reddit.NET/blob/master/src/Reddit.NET/RedditAPI.cs#L60-L65

**Comment by sirkris** [comment]
Merged into 1.3.

Usage Example:

```c#
RedditAPI reddit = new RedditAPI("AppId", "RefreshToken", userAgent: "My App or Library v1.0.0");
```

In the above example, all requests performed by the reddit instance will have a User-Agent of "My App or Library v1.0.0 (via Reddit.NET v1.2.0)".
