### ISSUE TITLE
how to get user post history from a specific subreddit

### ISSUE THREAD

**Issue by FireCubeStudios** [sirkris/Reddit.NET#89]
I want to know how to get post history from a user in a specific subreddit like r/aww where I get the users post from that specific subreddit.

im guessing its done by using reddit.account.me but I cant figure out where to go from there.

**Comment by sirkris** [comment]
Unfortunately, I don't think the API has a built-in way to do that.  As far as I know, all you can do is get a user's post history for all subreddits.  You would then have to iterate through the results in your code to discard the subreddits you don't want.

Another option would be to use the Search Controller, instead.  Then you could just do a subreddit search by author, like such:

```c#
List<Post> posts = reddit.Subreddit("facepalm").Search("author:KrisCraig");
```

**Comment by FireCubeStudios** [comment]
ok
