### ISSUE TITLE
Monitoring subredditposts stops firing events after 1 hour

### ISSUE THREAD

**Issue by ZwiebelTVDE** [sirkris/Reddit.NET#90]
I tried to monitor the posts on a subreddit but after roughly 1 hour the Posts_NewUpdated is not being triggered again

I tried it on multiple machines and networks to check if the network connection is a problem but iI assure you its not

**Comment by sirkris** [comment]
Very strange.  I have bots that have been successfully monitoring for weeks at a time, so there has to be something different happening on your end.  Could you post the code you're using?

**Comment by ZwiebelTVDE** [comment]
Oh damn, I forgot to clear this up. I fixed the problem with a refresh token. Its a bummer I can only create a refresh token involving a browser but I created a token and saved it in a config to run it in a headless bot. But thats besides the point and topic of another issue.

Thank you for your reply!
