### ISSUE TITLE
Get content out of post

### ISSUE THREAD

**Issue by Hirashi3630** [sirkris/Reddit.NET#91]
Hi I need help with getting content of post, I found issue #66 related to this question, but I can't make it work. I didn't find any documentation for this package (only examples).
I tried something like this:
```csharp
List<Post> SubTop = sub.Posts.Top;
foreach (SelfPost top in SubTop)
{
    Console.WriteLine(top.content);
}
```
I'd be so glad for answer! thx

**Comment by Hirashi3630** [comment]
Sorry for opening new issue but I was hopeless (or idiot?...)
I had idea to look for [repositories using Reddit.NET](https://github.com/sirkris/Reddit.NET/network/dependents?package_id=UGFja2FnZS0yOTYzMTE2OTY%3D) and I found solution in this repository called _RedditCuteGallery_ exactly [here](https://github.com/Ulkio/RedditCuteGallery/blob/master/gallery/gallery/MainPage.xaml.cs)

and for ppl with same problem here is my code:
```csharp
RedditAPI _Reddit = new RedditAPI(appId, refreshToken, accessToken);
var getHotPosts = _Reddit.Models.Listings.Hot(new Reddit.Inputs.Listings.ListingsHotInput(limit: 20), "funny").Data.Children;

foreach (var hotPost in getHotPosts)
{
	if ((hotPost.Data.URL.Contains("jpg") || hotPost.Data.URL.Contains("png")))
	{
		string url = hotPost.Data.URL;
		Console.WriteLine(url);
	}
}
```

**Comment by sirkris** [comment]
While the code you're using will work, it is not the optimal way to do this.  Reddit.NET is divided into two main areas:  Models and Controllers.  The Controllers call the Models, which in turn handle all the appropriate REST stuff.  Then the result goes back to the calling Controller, which organizes the data into a more useful/efficient structure and returns it.

What your code does is bypass these Controllers by accessing the Model directly, which should only be done in situations where there's some pressing reason not to use the controllers, and that doesn't apply to most cases.  

The RedditCuteGallery code is technically accurate but does not conform to the recommended guidelines I outlined above.  As such, I would not recommend relying on that project for examples.  I realize the lack of documentation is something I need to deal with at some point; in the meantime, your best bet if you get stuck is to open an issue here like you did.  I may not always be prompt in responding, but I will get around to it eventually.  =)

I would recommend you rewrite your code as follows:

```c#
RedditAPI _Reddit = new RedditAPI(appId, refreshToken, accessToken);

var getHotPosts = _Reddit.Subreddit("funny").Posts.GetHot(limit: 20);
foreach (var hotPost in getHotPosts)
{
    if (hotPost.URL.Contains(".jpg") || hotPost.URL.Contains(".png"))
    {
        Console.WriteLine(hotPost.URL);
    }
}
```

Hope this helps!

**Comment by Hirashi3630** [comment]
_WOW thx a lot, I didn't want to bother so I closed the issue._

> I realize the lack of documentation is something I need to deal with at some point;

Docs'd be great!

> In this example, only the first reference to .Hot will trigger an API call; the rest will simply reuse the results from the first. If you use .GetHot() directly, instead, it'll just make the API call every time (though it still updates the .Hot cache).

another what I wanted to ask lol - good2know

**again thx a LOT for the reply and solution**
